In [1]:
import tensorflow as tf
tf.enable_eager_execution()


In [2]:
def _parse_function(example_proto):
    features = {"inputs": tf.VarLenFeature(tf.int64),
              "targets": tf.VarLenFeature(tf.int64)}
    parsed_features = tf.parse_single_example(example_proto, features)
    inputs = tf.sparse_tensor_to_dense(parsed_features["inputs"])
    targets = tf.sparse_tensor_to_dense(parsed_features["targets"])
    return {"inputs":inputs,"targets":targets}


In [5]:
dataset = tf.data.TFRecordDataset("data/wmt32k-train-00001-of-00100")
dataset = dataset.map(_parse_function)
batched_dataset = dataset.batch(1)
batched_dataset

<DatasetV1Adapter shapes: {inputs: (?, ?), targets: (?, ?)}, types: {inputs: tf.int64, targets: tf.int64}>

In [8]:
for i,d in enumerate(batched_dataset):
    if i>2:
        break
    print(d['inputs'])
    print(d['targets'])
    print("===========================")

tf.Tensor(
[[   30   550    23  8695     2     6    97  2957  1302    17  2560     6
      4   261     2  1105   245  1277    27   838  1105    17     2     6
   4548    31  1855  1896     2     4   315  2599   118    28 13772   190
   2662  6281   114     4   129 17012     4  9691  1576     7     4  3785
      7     4   451  3887   123 18168   297  8516     8     4   451 29793
    297  8516     3     1]], shape=(1, 64), dtype=int64)
tf.Tensor(
[[   74   348 28227    22  6681     2     9    60   333  8498 24451    24
      2 17103   317    11 32678  7751  2886   413  2532   150     2    21
    399    11    41  4676    11 20512    29  5431    41 33025  6480   131
     11   105  1095 10209 32890     6    20 22032 13358  3894 12070    12
     11   311    20 13178 21007    11  1839    37 26981    14   162 33137
      5    15 11944   224    39    60 10938   162  6317 28899    29   224
  11573     3     1]], shape=(1, 75), dtype=int64)
tf.Tensor(
[[  303 10742     5    79  1264   166     2  